import type { InstructorQuiz, StudentQuiz } from "@/types/quiz";

// Sample instructor quizzes
export const sampleInstructorQuizzes: InstructorQuiz[] = [
  {
    id: "quiz-1",
    title: "JavaScript Fundamentals Quiz",
    author: {
      id: "author-1",
      name: "Dr. Sarah Chen",
      role: "instructor",
      initials: "SC",
    },
    createdAt: new Date("2025-12-15"),
    deadline: new Date("2025-12-30T23:59:59Z"),
    timeLimitMin: 30,
    status: "published",
    totalPoints: 50,
    questions: [
      {
        id: "q1",
        text: "What is the correct syntax for referring to an external script?",
        options: [
          "<script src='script.js'>",
          "<script href='script.js'>",
          "<script name='script.js'>",
          "<script file='script.js'>",
        ],
        correctOption: "<script src='script.js'>",
        points: 10,
      },
      {
        id: "q2",
        text: "Which operator is used to assign a value to a variable?",
        options: ["==", "=", "===", "!="],
        correctOption: "=",
        points: 10,
      },
      {
        id: "q3",
        text: "How do you declare a JavaScript variable?",
        options: [
          "v carName;",
          "variable carName;",
          "var carName;",
          "vr carName;",
        ],
        correctOption: "var carName;",
        points: 10,
      },
      {
        id: "q4",
        text: "How do you create a function in JavaScript?",
        options: [
          "function = myFunction()",
          "function myFunction()",
          "function:myFunction()",
          "create myFunction()",
        ],
        correctOption: "function myFunction()",
        points: 10,
      },
      {
        id: "q5",
        text: "How do you call a function named myFunction?",
        options: [
          "call myFunction()",
          "myFunction()",
          "call function myFunction",
          "execute myFunction()",
        ],
        correctOption: "myFunction()",
        points: 10,
      },
    ],
    submissionStats: {
      attempted: 18,
      total: 25,
      averageScore: 76,
    },
  },
  {
    id: "quiz-2",
    title: "React Hooks Quiz",
    author: {
      id: "author-1",
      name: "Dr. Sarah Chen",
      role: "instructor",
      initials: "SC",
    },
    createdAt: new Date("2025-12-18"),
    deadline: new Date("2026-01-05T23:59:59Z"),
    timeLimitMin: 45,
    status: "published",
    totalPoints: 40,
    questions: [
      {
        id: "q1",
        text: "Which hook is used to manage state in functional components?",
        options: ["useEffect", "useState", "useContext", "useReducer"],
        correctOption: "useState",
        points: 10,
      },
      {
        id: "q2",
        text: "Which hook is used for side effects?",
        options: ["useState", "useRef", "useEffect", "useMemo"],
        correctOption: "useEffect",
        points: 10,
      },
      {
        id: "q3",
        text: "What does useRef return?",
        options: [
          "A function",
          "A mutable object",
          "A state value",
          "A promise",
        ],
        correctOption: "A mutable object",
        points: 10,
      },
      {
        id: "q4",
        text: "Which hook avoids unnecessary re-renders?",
        options: ["useCallback", "useState", "useEffect", "useContext"],
        correctOption: "useCallback",
        points: 10,
      },
    ],
    submissionStats: {
      attempted: 5,
      total: 25,
      averageScore: 82,
    },
  },
  {
    id: "quiz-3",
    title: "CSS Flexbox Quiz",
    author: {
      id: "author-1",
      name: "Dr. Sarah Chen",
      role: "instructor",
      initials: "SC",
    },
    createdAt: new Date("2025-12-10"),
    deadline: new Date("2025-12-18T23:59:59Z"),
    timeLimitMin: 20,
    status: "closed",
    totalPoints: 30,
    questions: [
      {
        id: "q1",
        text: "What property makes an element a flex container?",
        options: [
          "display: block",
          "display: flex",
          "flex: 1",
          "position: flex",
        ],
        correctOption: "display: flex",
        points: 10,
      },
      {
        id: "q2",
        text: "Which property aligns items on the main axis?",
        options: [
          "align-items",
          "justify-content",
          "flex-direction",
          "flex-wrap",
        ],
        correctOption: "justify-content",
        points: 10,
      },
      {
        id: "q3",
        text: "What is the default flex-direction?",
        options: ["column", "row", "row-reverse", "column-reverse"],
        correctOption: "row",
        points: 10,
      },
    ],
    submissionStats: {
      attempted: 23,
      total: 25,
      averageScore: 89,
    },
  },
];

// Sample student quizzes
export const sampleStudentQuizzes: StudentQuiz[] = [
  {
    id: "quiz-1",
    title: "JavaScript Fundamentals Quiz",
    author: {
      id: "author-1",
      name: "Dr. Sarah Chen",
      role: "instructor",
      initials: "SC",
    },
    createdAt: new Date("2025-12-15"),
    deadline: new Date("2025-12-30T23:59:59Z"),
    timeLimitMin: 30,
    status: "published",
    totalPoints: 50,
    questions: [
      {
        id: "q1",
        text: "What is the correct syntax for referring to an external script?",
        options: [
          "<script src='script.js'>",
          "<script href='script.js'>",
          "<script name='script.js'>",
          "<script file='script.js'>",
        ],
        correctOption: "<script src='script.js'>",
        points: 10,
      },
      {
        id: "q2",
        text: "Which operator is used to assign a value to a variable?",
        options: ["==", "=", "===", "!="],
        correctOption: "=",
        points: 10,
      },
      {
        id: "q3",
        text: "How do you declare a JavaScript variable?",
        options: [
          "v carName;",
          "variable carName;",
          "var carName;",
          "vr carName;",
        ],
        correctOption: "var carName;",
        points: 10,
      },
      {
        id: "q4",
        text: "How do you create a function in JavaScript?",
        options: [
          "function = myFunction()",
          "function myFunction()",
          "function:myFunction()",
          "create myFunction()",
        ],
        correctOption: "function myFunction()",
        points: 10,
      },
      {
        id: "q5",
        text: "How do you call a function named myFunction?",
        options: [
          "call myFunction()",
          "myFunction()",
          "call function myFunction",
          "execute myFunction()",
        ],
        correctOption: "myFunction()",
        points: 10,
      },
    ],
    attempt: {
      status: "pending",
    },
  },
  {
    id: "quiz-2",
    title: "React Hooks Quiz",
    author: {
      id: "author-1",
      name: "Dr. Sarah Chen",
      role: "instructor",
      initials: "SC",
    },
    createdAt: new Date("2025-12-18"),
    deadline: new Date("2026-01-05T23:59:59Z"),
    timeLimitMin: 45,
    status: "published",
    totalPoints: 40,
    questions: [
      {
        id: "q1",
        text: "Which hook is used to manage state in functional components?",
        options: ["useEffect", "useState", "useContext", "useReducer"],
        correctOption: "useState",
        points: 10,
      },
      {
        id: "q2",
        text: "Which hook is used for side effects?",
        options: ["useState", "useRef", "useEffect", "useMemo"],
        correctOption: "useEffect",
        points: 10,
      },
      {
        id: "q3",
        text: "What does useRef return?",
        options: [
          "A function",
          "A mutable object",
          "A state value",
          "A promise",
        ],
        correctOption: "A mutable object",
        points: 10,
      },
      {
        id: "q4",
        text: "Which hook avoids unnecessary re-renders?",
        options: ["useCallback", "useState", "useEffect", "useContext"],
        correctOption: "useCallback",
        points: 10,
      },
    ],
    attempt: {
      id: "attempt-1",
      attemptedAt: new Date("2025-12-19T14:30:00Z"),
      status: "completed",
      score: 35,
      totalPoints: 40,
    },
  },
  {
    id: "quiz-3",
    title: "CSS Flexbox Quiz",
    author: {
      id: "author-1",
      name: "Dr. Sarah Chen",
      role: "instructor",
      initials: "SC",
    },
    createdAt: new Date("2025-12-10"),
    deadline: new Date("2025-12-18T23:59:59Z"),
    timeLimitMin: 20,
    status: "closed",
    totalPoints: 30,
    questions: [
      {
        id: "q1",
        text: "What property makes an element a flex container?",
        options: [
          "display: block",
          "display: flex",
          "flex: 1",
          "position: flex",
        ],
        correctOption: "display: flex",
        points: 10,
      },
      {
        id: "q2",
        text: "Which property aligns items on the main axis?",
        options: [
          "align-items",
          "justify-content",
          "flex-direction",
          "flex-wrap",
        ],
        correctOption: "justify-content",
        points: 10,
      },
      {
        id: "q3",
        text: "What is the default flex-direction?",
        options: ["column", "row", "row-reverse", "column-reverse"],
        correctOption: "row",
        points: 10,
      },
    ],
    attempt: {
      status: "missed",
    },
  },
];
