

"use client";

import React, { useState } from "react";
import {
  Phone,
  Mic,
  MicOff,
  Video,
  VideoOff,
  MonitorUp,
  Users,
  MessageSquare,
  Palette,
  Folder,
  Settings,
  MoreVertical,
  MicOffIcon,
  UserX,
  Shield,
  Layout,
  Maximize2,
  Volume2,
} from "lucide-react";
import ChatPanel from "@/components/live-session/ChatPanelSimplified";
import CanvasStage from "@/components/live-session/CanvasStage";
import FilesPanel from "@/components/live-session/FilesPanel";
import Toast from "@/components/live-session/Toast";
import {
  mockAttendees,
  mockSession,
  mockChatMessages,
  mockFiles,
  mockCanvasElements,
} from "@/lib/constants/live-session-mock-data";
import type { ChatMessage, Attendee, CanvasElement, SessionFile } from "@/types/live-session";

type ViewMode = "video" | "canvas" | "files";

export default function LiveSessionDemoPage() {
  // Host controls state
  const [micOn, setMicOn] = useState(true);
  const [cameraOn, setCameraOn] = useState(true);
  const [screenSharing, setScreenSharing] = useState(false);
  const [viewMode, setViewMode] = useState<ViewMode>("video");
  const [showSettings, setShowSettings] = useState(false);

  // Right sidebar state
  const [showSidebar, setShowSidebar] = useState(true);
  const [sidebarTab, setSidebarTab] = useState<"chat" | "attendees">("chat");

  // Data state
  const [attendees] = useState<Attendee[]>(mockAttendees);
  const [messages, setMessages] = useState<ChatMessage[]>(mockChatMessages);
  const [files] = useState<SessionFile[]>(mockFiles);
  const [canvasElements, setCanvasElements] = useState<CanvasElement[]>(mockCanvasElements);
  const [canvasLocked, setCanvasLocked] = useState(false);
  const [hoveredAttendee, setHoveredAttendee] = useState<string | null>(null);
  const [activeMenu, setActiveMenu] = useState<string | null>(null);

  // Toast state
  const [toast, setToast] = useState<{
    type: "success" | "error" | "info" | "warning";
    message: string;
  } | null>(null);

  const showToast = (type: "success" | "error" | "info" | "warning", message: string) => {
    setToast({ type, message });
  };

  // Host actions
  const handleEndCall = () => {
    if (window.confirm("End session for all participants?")) {
      console.log("[Host] Ending session for all participants");
      showToast("warning", "Session ended for all participants");
    }
  };

  const handleToggleMic = () => {
    setMicOn(!micOn);
    console.log(`[Host] Microphone ${!micOn ? "unmuted" : "muted"}`);
    showToast("info", `Microphone ${!micOn ? "unmuted" : "muted"}`);
  };

  const handleToggleCamera = () => {
    setCameraOn(!cameraOn);
    console.log(`[Host] Camera ${!cameraOn ? "enabled" : "disabled"}`);
    showToast("info", `Camera ${!cameraOn ? "enabled" : "disabled"}`);
  };

  const handleToggleScreenShare = () => {
    setScreenSharing(!screenSharing);
    console.log(`[Host] Screen sharing ${!screenSharing ? "started" : "stopped"}`);
    showToast("info", `Screen sharing ${!screenSharing ? "started" : "stopped"}`);
  };

  // Attendee actions
  const handleMuteAttendee = (id: string, name: string) => {
    console.log(`[Host] Muting attendee: ${name} (${id})`);
    showToast("info", `${name} has been muted`);
    setActiveMenu(null);
  };

  const handleRemoveAttendee = (id: string, name: string) => {
    if (window.confirm(`Remove ${name} from the session?`)) {
      console.log(`[Host] Removing attendee: ${name} (${id})`);
      showToast("warning", `${name} has been removed`);
      setActiveMenu(null);
    }
  };

  const handlePromoteAttendee = (id: string, name: string) => {
    console.log(`[Host] Promoting ${name} to co-host`);
    showToast("info", `${name} is now a co-host`);
    setActiveMenu(null);
  };

  // Chat actions
  const handleSendMessage = (content: string, askBot: boolean) => {
    console.log(`[Chat] Sending message: "${content}" ${askBot ? "(with bot query)" : ""}`);
    
    const newMessage: ChatMessage = {
      id: `msg-${Date.now()}`,
      senderId: "host-1",
      senderName: "Dr. Sarah Johnson",
      message: content,
      timestamp: new Date(),
      upvotes: 0,
      upvotedBy: [],
      isBotQuery: askBot,
    };

    setMessages([...messages, newMessage]);

    if (askBot) {
      setTimeout(() => {
        const botReply = {
          id: `bot-${Date.now()}`,
          question: content,
          answer: "This is a simulated bot response. In production, this would be generated by an AI assistant.",
          content: "This is a simulated bot response. In production, this would be generated by an AI assistant.",
          timestamp: new Date(),
          helpful: null,
          sources: ["Course Material", "Lecture Notes"],
        };
        
        setMessages((prev) =>
          prev.map((msg) =>
            msg.id === newMessage.id ? { ...msg, botReply } : msg
          )
        );
        showToast("info", "Bot replied to your question");
      }, 1500);
    }
  };

  const handleUpvoteMessage = (messageId: string) => {
    console.log(`[Chat] Upvoting message: ${messageId}`);
    setMessages((prev) =>
      prev.map((msg) =>
        msg.id === messageId
          ? { ...msg, upvotes: msg.upvotes + 1, upvotedBy: [...msg.upvotedBy, "host-1"] }
          : msg
      )
    );
  };

  const handleDeleteMessage = (messageId: string) => {
    console.log(`[Chat] Deleting message: ${messageId}`);
    setMessages((prev) => prev.filter((msg) => msg.id !== messageId));
    showToast("info", "Message deleted");
  };

  const handlePinMessage = (messageId: string) => {
    console.log(`[Chat] Pinning message: ${messageId}`);
    showToast("info", "Message pinned");
  };

  // Canvas actions
  const handleAddCanvasElement = (element: Omit<CanvasElement, "id">) => {
    const newElement = { ...element, id: `canvas-${Date.now()}` };
    setCanvasElements([...canvasElements, newElement]);
  };

  const handleUpdateCanvasElement = (id: string, updates: Partial<CanvasElement>) => {
    setCanvasElements((prev) =>
      prev.map((el) => (el.id === id ? { ...el, ...updates } : el))
    );
  };

  const handleDeleteCanvasElement = (id: string) => {
    setCanvasElements((prev) => prev.filter((el) => el.id !== id));
  };

  const handleToggleCanvasLock = () => {
    setCanvasLocked(!canvasLocked);
  };

  const handleCanvasUndo = () => {
    console.log("[Canvas] Undo last action");
  };

  const handleCanvasRedo = () => {
    console.log("[Canvas] Redo last action");
  };

  const handleClearCanvas = () => {
    setCanvasElements([]);
  };

  const handleExportCanvas = () => {
    console.log("[Canvas] Exporting canvas");
    showToast("info", "Canvas exported successfully");
  };

  // Files actions
  const handleDeleteFile = (fileId: string) => {
    console.log(`[Files] Deleting file: ${fileId}`);
    showToast("info", "File deleted");
  };

  // Control button component with tooltip
  const ControlButton = ({
    icon: Icon,
    label,
    onClick,
    isActive,
    variant = "default",
    shortcut,
  }: {
    icon: any;
    label: string;
    onClick: () => void;
    isActive?: boolean;
    variant?: "default" | "danger" | "primary";
    shortcut?: string;
  }) => {
    const baseClasses = "relative group p-3 rounded-full transition-all";
    const variantClasses = {
      default: isActive
        ? "bg-secondary text-white"
        : "bg-white hover:bg-gray-100 text-para border border-light-border",
      danger: "bg-destructive hover:bg-destructive/90 text-white",
      primary: isActive
        ? "bg-primary text-white"
        : "bg-white hover:bg-gray-100 text-para border border-light-border",
    };

    return (
      <button
        onClick={onClick}
        className={`${baseClasses} ${variantClasses[variant]}`}
        aria-label={label}
      >
        <Icon className="w-5 h-5" />
        
        {/* Tooltip */}
        <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 px-3 py-1.5 bg-gray-900 text-white text-xs rounded-lg opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none whitespace-nowrap z-50">
          {label}
          {shortcut && (
            <span className="ml-2 px-1.5 py-0.5 bg-white/20 rounded text-[10px]">
              {shortcut}
            </span>
          )}
          <div className="absolute top-full left-1/2 -translate-x-1/2 -mt-1 border-4 border-transparent border-t-gray-900" />
        </div>
      </button>
    );
  };

  return (
    <div className="h-screen flex flex-col bg-gray-50">
      {/* Toast */}
      {toast && (
        <div className="fixed top-4 right-4 z-50">
          <Toast type={toast.type} message={toast.message} onClose={() => setToast(null)} />
        </div>
      )}

      {/* Top Bar */}
      <div className="bg-white border-b border-light-border px-6 py-3 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-primary rounded-lg flex items-center justify-center text-white font-bold text-sm">
              M
            </div>
            <div>
              <h1 className="text-base font-bold text-heading">{mockSession.title}</h1>
              <p className="text-xs text-para-muted">{attendees.length} participants</p>
            </div>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {mockSession.isRecording && (
            <div className="flex items-center gap-2 px-3 py-1.5 bg-destructive/10 rounded-full">
              <div className="w-2 h-2 bg-destructive rounded-full animate-pulse" />
              <span className="text-xs font-medium text-destructive">Recording</span>
            </div>
          )}
          <span className="text-sm text-para-muted font-mono">45:32</span>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 flex overflow-hidden">
        {/* Main Video/Canvas/Files Area */}
        <div className="flex-1 flex flex-col bg-gray-100">
          {/* Content Area */}
          <div className="flex-1 p-4 overflow-auto">
            {viewMode === "video" && (
              <div className="h-full">
                {/* Video Grid */}
                <div className="grid grid-cols-4 gap-3 h-full">
                  {/* Host - Larger tile */}
                  <div className="col-span-2 row-span-2 relative bg-gradient-to-br from-primary/10 to-secondary/10 rounded-xl overflow-hidden group border border-light-border">
                    <div className="absolute inset-0 flex items-center justify-center">
                      <div className="text-center">
                        <div className="w-24 h-24 rounded-full bg-primary flex items-center justify-center text-white text-3xl font-bold mx-auto mb-3">
                          SJ
                        </div>
                        <p className="text-xl font-semibold text-heading">Dr. Sarah Johnson</p>
                        <span className="inline-block mt-1 px-2 py-1 bg-primary/10 text-primary text-xs font-medium rounded">
                          Host (You)
                        </span>
                      </div>
                    </div>

                    {/* Status indicators */}
                    <div className="absolute bottom-3 left-3 flex items-center gap-2">
                      {micOn && (
                        <div className="p-1.5 bg-white rounded-full shadow-sm">
                          <Volume2 className="w-3 h-3 text-primary" />
                        </div>
                      )}
                      {!micOn && (
                        <div className="p-1.5 bg-destructive rounded-full shadow-sm">
                          <MicOff className="w-3 h-3 text-white" />
                        </div>
                      )}
                    </div>

                    {/* Name tag */}
                    <div className="absolute bottom-3 right-3 px-2 py-1 bg-black/50 backdrop-blur-sm rounded text-white text-sm">
                      You
                    </div>
                  </div>

                  {/* Other attendees */}
                  {attendees.slice(1, 7).map((attendee) => (
                    <div
                      key={attendee.id}
                      className="relative bg-white rounded-xl overflow-hidden group border border-light-border"
                      onMouseEnter={() => setHoveredAttendee(attendee.id)}
                      onMouseLeave={() => setHoveredAttendee(null)}
                    >
                      <div className="absolute inset-0 flex items-center justify-center bg-gradient-to-br from-secondary/5 to-primary/5">
                        {attendee.webcamOn ? (
                          <div className="text-center">
                            <div className="w-16 h-16 rounded-full bg-secondary flex items-center justify-center text-white text-lg font-bold mx-auto">
                              {attendee.name.split(" ").map((n) => n[0]).join("").toUpperCase().slice(0, 2)}
                            </div>
                          </div>
                        ) : (
                          <div className="text-center">
                            <div className="w-16 h-16 rounded-full bg-secondary flex items-center justify-center text-white text-lg font-bold mx-auto mb-2">
                              {attendee.name.split(" ").map((n) => n[0]).join("").toUpperCase().slice(0, 2)}
                            </div>
                            <VideoOff className="w-5 h-5 text-para-muted mx-auto" />
                          </div>
                        )}
                      </div>

                      {/* Status indicators */}
                      <div className="absolute bottom-3 left-3 flex items-center gap-1">
                        {attendee.speakerActive && (
                          <div className="p-1 bg-primary rounded-full shadow-sm animate-pulse">
                            <Volume2 className="w-3 h-3 text-white" />
                          </div>
                        )}
                        {!attendee.micOn && (
                          <div className="p-1 bg-destructive/90 rounded-full shadow-sm">
                            <MicOff className="w-3 h-3 text-white" />
                          </div>
                        )}
                      </div>

                      {/* Name tag */}
                      <div className="absolute bottom-3 right-3 px-2 py-1 bg-black/50 backdrop-blur-sm rounded text-white text-xs max-w-[120px] truncate">
                        {attendee.name}
                      </div>

                      {/* Three-dot menu */}
                      <div className={`absolute top-2 right-2 transition-opacity ${hoveredAttendee === attendee.id ? "opacity-100" : "opacity-0"}`}>
                        <button
                          onClick={() => setActiveMenu(activeMenu === attendee.id ? null : attendee.id)}
                          className="p-1.5 bg-white rounded-lg shadow-lg hover:bg-background transition-colors"
                        >
                          <MoreVertical className="w-4 h-4 text-para" />
                        </button>

                        {/* Dropdown menu */}
                        {activeMenu === attendee.id && (
                          <>
                            <div
                              className="fixed inset-0 z-10"
                              onClick={() => setActiveMenu(null)}
                            />
                            <div className="absolute right-0 top-full mt-1 z-20 bg-white border border-light-border rounded-lg shadow-xl py-1 min-w-[160px]">
                              <button
                                onClick={() => handleMuteAttendee(attendee.id, attendee.name)}
                                className="w-full px-3 py-2 text-left text-sm text-para hover:bg-background flex items-center gap-2"
                              >
                                <MicOffIcon className="w-4 h-4" />
                                Mute
                              </button>
                              <button
                                onClick={() => handlePromoteAttendee(attendee.id, attendee.name)}
                                className="w-full px-3 py-2 text-left text-sm text-para hover:bg-background flex items-center gap-2"
                              >
                                <Shield className="w-4 h-4" />
                                Make Co-host
                              </button>
                              <div className="h-px bg-light-border my-1" />
                              <button
                                onClick={() => handleRemoveAttendee(attendee.id, attendee.name)}
                                className="w-full px-3 py-2 text-left text-sm text-destructive hover:bg-destructive/5 flex items-center gap-2"
                              >
                                <UserX className="w-4 h-4" />
                                Remove
                              </button>
                            </div>
                          </>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {viewMode === "canvas" && (
              <div className="h-full bg-white rounded-xl border border-light-border overflow-hidden">
                <CanvasStage
                  elements={canvasElements}
                  isLocked={canvasLocked}
                  onAddElement={handleAddCanvasElement}
                  onUpdateElement={handleUpdateCanvasElement}
                  onDeleteElement={handleDeleteCanvasElement}
                  onToggleLock={handleToggleCanvasLock}
                  onUndo={handleCanvasUndo}
                  onRedo={handleCanvasRedo}
                  onClear={handleClearCanvas}
                  onExport={handleExportCanvas}
                />
              </div>
            )}

            {viewMode === "files" && (
              <div className="h-full bg-white rounded-xl border border-light-border overflow-hidden">
                <FilesPanel files={files} onDeleteFile={handleDeleteFile} />
              </div>
            )}
          </div>

          {/* Bottom Control Bar */}
          <div className="bg-white border-t border-light-border px-6 py-4">
            <div className="flex items-center justify-between max-w-5xl mx-auto">
              {/* Left: End Call */}
              <ControlButton
                icon={Phone}
                label="End Call"
                onClick={handleEndCall}
                variant="danger"
              />

              {/* Center: Main Controls */}
              <div className="flex items-center gap-3">
                <ControlButton
                  icon={micOn ? Mic : MicOff}
                  label={micOn ? "Mute" : "Unmute"}
                  onClick={handleToggleMic}
                  isActive={!micOn}
                  variant="default"
                  shortcut="M"
                />
                <ControlButton
                  icon={cameraOn ? Video : VideoOff}
                  label={cameraOn ? "Turn off camera" : "Turn on camera"}
                  onClick={handleToggleCamera}
                  isActive={!cameraOn}
                  variant="default"
                  shortcut="C"
                />
                <ControlButton
                  icon={MonitorUp}
                  label={screenSharing ? "Stop sharing" : "Share screen"}
                  onClick={handleToggleScreenShare}
                  isActive={screenSharing}
                  variant="default"
                  shortcut="S"
                />
              </div>

              {/* Right: View Controls */}
              <div className="flex items-center gap-2">
                <ControlButton
                  icon={Layout}
                  label="Grid view"
                  onClick={() => setViewMode("video")}
                  isActive={viewMode === "video"}
                  variant="primary"
                />
                <ControlButton
                  icon={Palette}
                  label="Whiteboard"
                  onClick={() => setViewMode(viewMode === "canvas" ? "video" : "canvas")}
                  isActive={viewMode === "canvas"}
                  variant="primary"
                />
                <ControlButton
                  icon={Folder}
                  label="Files"
                  onClick={() => setViewMode(viewMode === "files" ? "video" : "files")}
                  isActive={viewMode === "files"}
                  variant="primary"
                />
                <ControlButton
                  icon={showSidebar ? MessageSquare : Users}
                  label="Toggle sidebar"
                  onClick={() => setShowSidebar(!showSidebar)}
                  isActive={showSidebar}
                  variant="primary"
                />
              </div>
            </div>
          </div>
        </div>

        {/* Right Sidebar - Chat with Attendees List */}
        {showSidebar && (
          <div className="w-80 bg-white border-l border-light-border flex flex-col">
            {/* Tabs */}
            <div className="flex border-b border-light-border">
              <button
                onClick={() => setSidebarTab("chat")}
                className={`flex-1 px-4 py-3 text-sm font-medium transition-colors ${
                  sidebarTab === "chat"
                    ? "text-primary border-b-2 border-primary bg-primary/5"
                    : "text-para hover:bg-background"
                }`}
              >
                Chat
              </button>
              <button
                onClick={() => setSidebarTab("attendees")}
                className={`flex-1 px-4 py-3 text-sm font-medium transition-colors ${
                  sidebarTab === "attendees"
                    ? "text-primary border-b-2 border-primary bg-primary/5"
                    : "text-para hover:bg-background"
                }`}
              >
                Attendees ({attendees.length})
              </button>
            </div>

            {/* Content */}
            <div className="flex-1 overflow-hidden">
              {sidebarTab === "chat" ? (
                <ChatPanel
                  messages={messages}
                  currentUserId="host-1"
                  onSendMessage={handleSendMessage}
                  onUpvoteMessage={handleUpvoteMessage}
                  onDeleteMessage={handleDeleteMessage}
                  onPinMessage={handlePinMessage}
                />
              ) : (
                <div className="h-full overflow-y-auto">
                  <div className="p-3 space-y-2">
                    {attendees.map((attendee) => (
                      <div
                        key={attendee.id}
                        className="flex items-center gap-3 p-2 rounded-lg hover:bg-background transition-colors group"
                      >
                        {/* Avatar */}
                        <div className="relative">
                          <div className="w-10 h-10 rounded-full bg-secondary flex items-center justify-center text-white text-sm font-bold">
                            {attendee.name.split(" ").map((n) => n[0]).join("").toUpperCase().slice(0, 2)}
                          </div>
                          {attendee.speakerActive && (
                            <div className="absolute -bottom-0.5 -right-0.5 w-3 h-3 bg-primary rounded-full border-2 border-white" />
                          )}
                        </div>

                        {/* Info */}
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-medium text-heading truncate">
                            {attendee.name}
                            {attendee.role === "host" && " (Host)"}
                            {attendee.id === "host-1" && " (You)"}
                          </p>
                          <div className="flex items-center gap-2 text-xs text-para-muted">
                            {attendee.role === "co-host" && (
                              <span className="text-primary">Co-host</span>
                            )}
                          </div>
                        </div>

                        {/* Status Icons */}
                        <div className="flex items-center gap-1">
                          {attendee.micOn ? (
                            <Mic className="w-4 h-4 text-para-muted" />
                          ) : (
                            <MicOff className="w-4 h-4 text-destructive" />
                          )}
                          {attendee.webcamOn ? (
                            <Video className="w-4 h-4 text-para-muted" />
                          ) : (
                            <VideoOff className="w-4 h-4 text-para-muted" />
                          )}
                        </div>

                        {/* Three-dot menu (host only, not for self) */}
                        {attendee.id !== "host-1" && (
                          <div className="relative">
                            <button
                              onClick={() => setActiveMenu(activeMenu === `sidebar-${attendee.id}` ? null : `sidebar-${attendee.id}`)}
                              className="p-1 opacity-0 group-hover:opacity-100 hover:bg-gray-100 rounded transition-all"
                            >
                              <MoreVertical className="w-4 h-4 text-para" />
                            </button>

                            {activeMenu === `sidebar-${attendee.id}` && (
                              <>
                                <div
                                  className="fixed inset-0 z-10"
                                  onClick={() => setActiveMenu(null)}
                                />
                                <div className="absolute right-0 top-full mt-1 z-20 bg-white border border-light-border rounded-lg shadow-xl py-1 min-w-[160px]">
                                  <button
                                    onClick={() => handleMuteAttendee(attendee.id, attendee.name)}
                                    className="w-full px-3 py-2 text-left text-sm text-para hover:bg-background flex items-center gap-2"
                                  >
                                    <MicOffIcon className="w-4 h-4" />
                                    Mute
                                  </button>
                                  <button
                                    onClick={() => handlePromoteAttendee(attendee.id, attendee.name)}
                                    className="w-full px-3 py-2 text-left text-sm text-para hover:bg-background flex items-center gap-2"
                                  >
                                    <Shield className="w-4 h-4" />
                                    Make Co-host
                                  </button>
                                  <div className="h-px bg-light-border my-1" />
                                  <button
                                    onClick={() => handleRemoveAttendee(attendee.id, attendee.name)}
                                    className="w-full px-3 py-2 text-left text-sm text-destructive hover:bg-destructive/5 flex items-center gap-2"
                                  >
                                    <UserX className="w-4 h-4" />
                                    Remove
                                  </button>
                                </div>
                              </>
                            )}
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
