import type { Metadata } from "next";

import "./globals.css";
import { Toaster } from "sonner";
import { Roboto, Raleway } from "next/font/google";
import { CircleCheck } from "lucide-react";
const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
});
const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${raleway.variable} `}>
        {children}
        <Toaster
          icons={{
            success: (
              <CircleCheck className="h-5 w-5 text-green-600 text-center" />
            ),
          }}
        />
      </body>
    </html>
  );
}
