"use client";

import React, { useState, useRef, useEffect } from "react";
import { motion } from "motion/react";
import { PanelRightOpen, Sparkles } from "lucide-react";
import ChatMessage from "@/components/ai-assistant/ChatMessage";
import ChatComposer from "@/components/ai-assistant/ChatComposer";
import ChatHistory from "@/components/ai-assistant/ChatHistory";
import { sampleChatSessions } from "@/lib/constants/ai-chat-mock-data";
import type {
  ChatMessage as ChatMessageType,
  ContextFile,
} from "@/types/ai-chat";

export default function AIAssistantPage() {
  const [messages, setMessages] = useState<ChatMessageType[]>([]);
  const [contextFiles, setContextFiles] = useState<ContextFile[]>([]);
  const [activeSessionId, setActiveSessionId] = useState<string | null>(null);
  const [sessions, setSessions] = useState(sampleChatSessions);
  const [showHistory, setShowHistory] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Auto-scroll to bottom
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  // Handle send message
  const handleSendMessage = (content: string, files: ContextFile[]) => {
    const userMessage: ChatMessageType = {
      id: `msg-${Date.now()}`,
      role: "user",
      content,
      timestamp: new Date(),
      contextFiles: files.length > 0 ? files : undefined,
    };

    setMessages((prev) => [...prev, userMessage]);
    setIsGenerating(true);

    // Simulate AI response
    setTimeout(() => {
      const aiMessage: ChatMessageType = {
        id: `msg-${Date.now() + 1}`,
        role: "assistant",
        content:
          "I understand your question. Based on the context you've provided, here's my response:\n\nThis is a simulated response from the AI assistant. In a real implementation, this would be generated by your AI backend service, taking into account the conversation history and any context files you've attached.\n\nWould you like me to elaborate on any specific aspect?",
        timestamp: new Date(),
      };
      setMessages((prev) => [...prev, aiMessage]);
      setIsGenerating(false);
    }, 1500);
  };

  // Handle context file management
  const handleAddContext = () => {
    // Simulate adding context files from rooms
    const newFile: ContextFile = {
      id: `file-${Date.now()}`,
      name: "Lecture Notes - Week 5.pdf",
      type: "application/pdf",
      roomName: "Computer Science 101",
      roomId: "room-1",
      size: 1024 * 512,
    };
    setContextFiles((prev) => [...prev, newFile]);
  };

  const handleRemoveContextFile = (fileId: string) => {
    setContextFiles((prev) => prev.filter((f) => f.id !== fileId));
  };

  // Handle chat history
  const handleNewChat = () => {
    setMessages([]);
    setContextFiles([]);
    setActiveSessionId(null);
  };

  const handleSelectSession = (sessionId: string) => {
    setActiveSessionId(sessionId);
    // In real implementation, load messages for this session
  };

  const handleTogglePin = (sessionId: string) => {
    setSessions((prev) =>
      prev.map((s) =>
        s.id === sessionId ? { ...s, isPinned: !s.isPinned } : s
      )
    );
  };

  const handleSaveToNotes = (messageId: string) => {
    const message = messages.find((m) => m.id === messageId);
    if (message) {
      console.log("Save to notes:", message.content);
      // TODO: Implement save to notes functionality
      alert("This would save the message to your notes!");
    }
  };

  const handleRegenerate = (messageId: string) => {
    console.log("Regenerate response for:", messageId);
    // TODO: Implement regenerate functionality
  };

  return (
    <div className="h-screen flex overflow-hidden bg-main-background">
      {/* History Sidebar - Animated width like AppSidebar */}
      <motion.div
        animate={{
          width: showHistory ? "280px" : "0px",
        }}
        transition={{
          duration: 0.3,
          ease: "easeInOut",
        }}
        className="relative flex-shrink-0 overflow-hidden border-r border-light-border"
      >
        {showHistory && (
          <div className="w-[280px]">
            <ChatHistory
              sessions={sessions}
              activeSessionId={activeSessionId}
              onSelectSession={handleSelectSession}
              onNewChat={handleNewChat}
              onTogglePin={handleTogglePin}
              onClose={() => setShowHistory(false)}
              isMobile={false}
            />
          </div>
        )}
      </motion.div>

      {/* Main Chat Area */}
      <div className="flex-1 flex flex-col min-w-0 relative">
        {/* Minimal Header - Just toggle button */}
        <div className="absolute top-4 left-4 z-20">
          <button
            onClick={() => setShowHistory(!showHistory)}
            className="p-2 rounded-lg bg-main-background border border-light-border hover:bg-gray-50 transition-colors shadow-sm"
            title="Toggle Chat History"
          >
            <PanelRightOpen className={`w-5 h-5 text-para transition-transform ${showHistory ? 'rotate-180' : ''}`} />
          </button>
        </div>

        {/* Chat Content Area */}
        <div className="flex-1 flex flex-col overflow-hidden">
          {/* Welcome Section (when no messages) */}
          {messages.length === 0 && (
            <div className="flex-1 flex items-center justify-center p-6 pb-32">
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="max-w-2xl text-center"
              >
                <div className="w-20 h-20 mx-auto mb-6 rounded-full bg-gradient-to-br from-primary to-secondary flex items-center justify-center shadow-lg">
                  <Sparkles className="w-10 h-10 text-white" />
                </div>
                <h2 className="text-3xl font-raleway font-bold text-heading mb-3">
                  Good Morning, Judha
                </h2>
                <p className="text-lg text-para mb-8">
                  How Can I{" "}
                  <span className="text-primary font-semibold">
                    Assist You Today?
                  </span>
                </p>
              </motion.div>
            </div>
          )}

          {/* Messages Area */}
          {messages.length > 0 && (
            <div className="flex-1 overflow-y-auto px-4 sm:px-6 py-6 pb-44">
              <div className="max-w-3xl mx-auto">
                {messages.map((message) => (
                  <ChatMessage
                    key={message.id}
                    message={message}
                    onSaveToNotes={handleSaveToNotes}
                    onRegenerate={handleRegenerate}
                  />
                ))}

                {/* Loading Indicator */}
                {isGenerating && (
                  <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="flex gap-3 mb-6"
                  >
                    <div className="flex-shrink-0 w-9 h-9 rounded-full bg-gradient-to-br from-primary to-secondary flex items-center justify-center">
                      <Sparkles className="w-5 h-5 text-white" />
                    </div>
                    <div className="flex-1 max-w-[85%]">
                      <div className="rounded-2xl px-4 py-3 bg-main-background border border-light-border">
                        <div className="flex items-center gap-2">
                          <div className="w-2 h-2 rounded-full bg-primary animate-pulse" />
                          <div className="w-2 h-2 rounded-full bg-primary animate-pulse delay-75" />
                          <div className="w-2 h-2 rounded-full bg-primary animate-pulse delay-150" />
                          <span className="text-sm text-para-muted ml-2">
                            Thinking...
                          </span>
                        </div>
                      </div>
                    </div>
                  </motion.div>
                )}

                <div ref={messagesEndRef} />
              </div>
            </div>
          )}
        </div>

        {/* Composer - Fixed at bottom */}
        <div className="absolute w-full max-w-[700px] left-1/2 -translate-x-1/2 bottom-22 z-10 bg-red-500">
          <ChatComposer
            onSendMessage={handleSendMessage}
            onAddContext={handleAddContext}
            contextFiles={contextFiles}
            onRemoveContextFile={handleRemoveContextFile}
            disabled={isGenerating}
          />
        </div>
      </div>
    </div>
  );
}
